apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: prdauths.prd.persistent.com
spec:
  group: prd.persistent.com
  names:
    kind: PRDAUTH
    listKind: PRDAUTHList
    plural: prdauths
    singular: prdauth
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
