---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prd-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prd-operator
  template:
    metadata:
      labels:
        name: prd-operator
    spec:
      serviceAccountName: prd-operator
      containers:
        - name: prd-operator
          # Replace this with the built image name
          image: "prd-operator:v0.0.1"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "prd-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: ANSIBLE_DEBUG_LOGS
              value: "False"
      volumes:
        - name: runner
          emptyDir: {}
