---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: prdapp-config-backup-pv
    labels:
      purpose: prdapp-config-backup-pv
spec:
    storageClassName: standard
    capacity: 
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/prd/backup/prdapp"
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: prdauth-config-backup-pv
    labels:
      purpose: prdauth-config-backup-pv
spec:
    storageClassName: standard
    capacity: 
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/prd/backup/prdauth"
